# trigger workflow
name: CI Pipeline
on:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps

      - name: Run integration test (inside docker network)
        run: docker compose run --rm testserver

      # --- CD (Deploy para Docker Hub) só se testes DEREM CERTO ---
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image para Docker Hub
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flasktodo2:latest .

      - name: Push Docker image para Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flasktodo2:latest

      # --- Shutdown sempre (mantendo o if: always()) ---
      - name: Shutdown containers
        if: always()
        run: docker compose down
